// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/handlers.go

package http

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"
)

// MockRAGPipeline is a mock of RAGPipeline interface.
type MockRAGPipeline struct {
	ctrl     *gomock.Controller
	recorder *MockRAGPipelineMockRecorder
}

// MockRAGPipelineMockRecorder is the mock recorder for MockRAGPipeline.
type MockRAGPipelineMockRecorder struct {
	mock *MockRAGPipeline
}

// NewMockRAGPipeline creates a new mock instance.
func NewMockRAGPipeline(ctrl *gomock.Controller) *MockRAGPipeline {
	mock := &MockRAGPipeline{ctrl: ctrl}
	mock.recorder = &MockRAGPipelineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRAGPipeline) EXPECT() *MockRAGPipelineMockRecorder {
	return m.recorder
}

// Ingest mocks base method.
func (m *MockRAGPipeline) Ingest(ctx context.Context, text string, docID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ingest", ctx, text, docID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ingest indicates an expected call of Ingest.
func (mr *MockRAGPipelineMockRecorder) Ingest(ctx, text, docID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ingest", reflect.TypeOf((*MockRAGPipeline)(nil).Ingest), ctx, text, docID)
}

// Retrieve mocks base method.
func (m *MockRAGPipeline) Retrieve(ctx context.Context, query string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retrieve", ctx, query)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retrieve indicates an expected call of Retrieve.
func (mr *MockRAGPipelineMockRecorder) Retrieve(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockRAGPipeline)(nil).Retrieve), ctx, query)
}

