// Code generated by MockGen. DO NOT EDIT.
// Source: internal/rag/pipeline.go

package rag

import (
	"github.com/golang/mock/gomock"
	"reflect"
)

// MockTextChunker is a mock of TextChunker interface.
type MockTextChunker struct {
	ctrl     *gomock.Controller
	recorder *MockTextChunkerMockRecorder
}

// MockTextChunkerMockRecorder is the mock recorder for MockTextChunker.
type MockTextChunkerMockRecorder struct {
	mock *MockTextChunker
}

// NewMockTextChunker creates a new mock instance.
func NewMockTextChunker(ctrl *gomock.Controller) *MockTextChunker {
	mock := &MockTextChunker{ctrl: ctrl}
	mock.recorder = &MockTextChunkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextChunker) EXPECT() *MockTextChunkerMockRecorder {
	return m.recorder
}

// ChunkText mocks base method.
func (m *MockTextChunker) ChunkText(text string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChunkText", text)
	ret0, _ := ret[0].([]string)
	return ret0
}

// ChunkText indicates an expected call of ChunkText.
func (mr *MockTextChunkerMockRecorder) ChunkText(text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChunkText", reflect.TypeOf((*MockTextChunker)(nil).ChunkText), text)
}

