// Code generated by MockGen. DO NOT EDIT.
// Source: internal/rag/pipeline.go

package rag

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"
	"github.com/qdrant/go-client/qdrant"
)

// MockVectorDatabase is a mock of VectorDatabase interface.
type MockVectorDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockVectorDatabaseMockRecorder
}

// MockVectorDatabaseMockRecorder is the mock recorder for MockVectorDatabase.
type MockVectorDatabaseMockRecorder struct {
	mock *MockVectorDatabase
}

// NewMockVectorDatabase creates a new mock instance.
func NewMockVectorDatabase(ctrl *gomock.Controller) *MockVectorDatabase {
	mock := &MockVectorDatabase{ctrl: ctrl}
	mock.recorder = &MockVectorDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorDatabase) EXPECT() *MockVectorDatabaseMockRecorder {
	return m.recorder
}

// EnsureCollection mocks base method.
func (m *MockVectorDatabase) EnsureCollection(ctx context.Context, vectorSize uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureCollection", ctx, vectorSize)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureCollection indicates an expected call of EnsureCollection.
func (mr *MockVectorDatabaseMockRecorder) EnsureCollection(ctx, vectorSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureCollection", reflect.TypeOf((*MockVectorDatabase)(nil).EnsureCollection), ctx, vectorSize)
}

// Search mocks base method.
func (m *MockVectorDatabase) Search(ctx context.Context, queryEmbedding []float32, limit uint64) ([]string, []float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, queryEmbedding, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]float32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockVectorDatabaseMockRecorder) Search(ctx, queryEmbedding, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockVectorDatabase)(nil).Search), ctx, queryEmbedding, limit)
}

// UpsertPoints mocks base method.
func (m *MockVectorDatabase) UpsertPoints(ctx context.Context, pointsToUpsert []*qdrant.PointStruct) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPoints", ctx, pointsToUpsert)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPoints indicates an expected call of UpsertPoints.
func (mr *MockVectorDatabaseMockRecorder) UpsertPoints(ctx, pointsToUpsert interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPoints", reflect.TypeOf((*MockVectorDatabase)(nil).UpsertPoints), ctx, pointsToUpsert)
}

